name: Build Client

on:
    push:
        branches: [main]
    workflow_dispatch: # Manual dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: npm

            - run: npm ci

            - run: npm run build:client

            - name: Publish build to branch
              uses: peaceiris/actions-gh-pages@v4
              env:
                  VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: client/dist
                  publish_branch: build-client
                  force_orphan: true
