name: Build Server

on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - run: |
                  npm install
                  npm run build:server

            - name: Publish build to branch
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: server/dist
                  branch: build-out
